// Package config turns the process environment into the single Config value
// every other module reads. Nothing else in the server calls os.Getenv, so
// "what can be configured" is answerable by reading this one file.
//
// Every setting has a default that makes `./obsidian-arc` a working server:
// SQLite in ./data, a secret key generated and persisted on first run, an
// address on :8080. Deployment is then a matter of overriding the few things
// a real host cares about, not of filling in a required form.
package config

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
)

const envPrefix = "OBSIDIAN_"

// SecretKeyFile is where a generated key is persisted, relative to DataDir,
// when OBSIDIAN_SECRET_KEY is not set.
const SecretKeyFile = "secret.key"

// SSHHostKeyFile is where the console's SSH host key is persisted, relative
// to DataDir, when OBSIDIAN_SSH_HOST_KEY is not set.
const SSHHostKeyFile = "ssh_host_ed25519_key"

type Config struct {
	Addr     string
	DataDir  string
	Dev      bool
	LogLevel string
	// Whose forwarded headers are believed. Every rate limit is keyed on
	// the address this produces, so a caller able to choose it has no
	// limits at all.
	TrustProxy bool
	// Exact peers, when the proxy's address is known. Empty with
	// TrustProxy set falls back to the private ranges.
	TrustedProxies []string
	// The operator's claim that Cloudflare terminates in front of this
	// deployment. CF-Connecting-IP is only honored with it: nothing on the
	// request can distinguish Cloudflare's header from a forged one.
	TrustCloudflare bool
	// Extra origins accepted on state-changing requests, beyond the request's
	// own Host. Only needed when the SPA is served from somewhere else.
	AllowedOrigins []string
	// A directory of plugin packages (*.arcx) the deployment ships with,
	// read at boot: what the instance runs as plugins of an earlier build is
	// taken over, what is new is installed switched off, what an operator
	// installed or removed themselves is left as they decided. Empty, or a
	// directory that is not there, is none.
	PluginDir string

	Database  Database
	Session   Session
	Password  Password
	Upstream  Upstream
	Bootstrap Bootstrap
	Mail      Mail
	Console   Console

	// Encrypts provider API keys at rest. Never logged, never served.
	SecretKey []byte

	// True when SecretKey was generated by this process instead of supplied.
	generatedSecret bool
}

// Mail is optional. Without a host the server simply cannot offer the
// features that need it, which is a state the admin screen reports rather
// than a misconfiguration. These environment values are a fallback until
// an administrator saves a mail configuration in its own sealed table; the
// general settings table is served to a browser and cannot hold credentials.
type Mail struct {
	Host     string
	Port     int
	Username string
	Password string
	From     string
	// Implicit TLS from the first byte, as on 465. Otherwise the session
	// starts plain and is upgraded with STARTTLS, which is what 587 wants.
	ImplicitTLS bool
	// What a link in an outgoing message points at. The server cannot
	// infer this: the Host header of whichever request happened to
	// trigger the mail is not a base URL worth trusting.
	PublicURL string
}

// Console is the administrative console's second door: the same command
// engine the browser talks to, reachable over SSH.
//
// Off unless SSHAddr is set. A listener that appears because the software was
// upgraded is not a decision an operator made, and this one accepts
// passwords.
type Console struct {
	// "" disables SSH entirely; ":2222" is the usual value.
	SSHAddr string
	// Where the server's own identity lives. Generated on first start when
	// absent, which is what makes `ssh admin@host` work without setup — at
	// the cost of a fingerprint that changes if the data directory is lost.
	SSHHostKey string
	// How long a session may sit at a prompt doing nothing. A console session
	// holds an authenticated administrator, so it is not left open forever.
	SSHIdle time.Duration
	// Concurrent sessions across all accounts. Each one costs a goroutine and
	// an open connection, and nobody needs sixteen prompts.
	SSHMaxSessions int
}

type Database struct {
	Driver string // "sqlite" | "postgres"
	DSN    string
	// Ceiling on pooled connections. SQLite in WAL mode tolerates a handful
	// of concurrent readers; Postgres wants a small pool per instance.
	MaxOpenConns int
	MaxIdleConns int
	ConnMaxIdle  time.Duration
}

type Session struct {
	TTL          time.Duration
	CookieName   string
	SecureCookie bool
	// How stale sessions.last_seen_at may get before a request refreshes it.
	// Writing on every request would turn every read into a write.
	TouchInterval time.Duration
}

// Password holds the Argon2id parameters. The defaults are OWASP's second
// recommended profile (19 MiB, t=2, p=1); MaxParallel bounds how many hashes
// may run at once, so a burst of logins cannot multiply that memory cost
// across the whole process.
type Password struct {
	Memory      uint32
	Iterations  uint32
	Parallelism uint8
	SaltLength  uint32
	KeyLength   uint32
	MaxParallel int
}

type Upstream struct {
	DialTimeout           time.Duration
	ResponseHeaderTimeout time.Duration
	// Overall ceiling on one upstream call. Zero means no ceiling beyond the
	// request context, which is what a long generation needs.
	RequestTimeout  time.Duration
	MaxIdleConns    int
	IdleConnTimeout time.Duration
}

// Bootstrap is the first administrator, created only when the users table is
// empty. Leaving it unset on an empty database is not an error: the first
// account registered through the UI is promoted instead.
type Bootstrap struct {
	Username string
	Password string
	Email    string
}

func Load() (Config, error) {
	dataDir := env("DATA_DIR", "./data")
	abs, err := filepath.Abs(dataDir)
	if err != nil {
		return Config{}, fmt.Errorf("resolve data dir %q: %w", dataDir, err)
	}
	dataDir = abs
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		return Config{}, fmt.Errorf("create data dir %q: %w", dataDir, err)
	}

	dev := envBool("DEV", false)

	driver := strings.ToLower(env("DB_DRIVER", "sqlite"))
	switch driver {
	case "sqlite", "sqlite3":
		driver = "sqlite"
	case "postgres", "postgresql", "pgx":
		driver = "postgres"
	default:
		return Config{}, fmt.Errorf("unknown %sDB_DRIVER %q (want sqlite or postgres)", envPrefix, driver)
	}

	dsn := env("DB_DSN", "")
	if dsn == "" {
		if driver != "sqlite" {
			return Config{}, fmt.Errorf("%sDB_DSN is required when %sDB_DRIVER is %s", envPrefix, envPrefix, driver)
		}
		dsn = filepath.Join(dataDir, "obsidian.db")
	}

	// SQLite serialises writers no matter how many handles are open, so a
	// large pool buys nothing and costs file descriptors.
	maxConns := 4
	if driver == "postgres" {
		maxConns = 10
	}

	secret, generated, err := loadOrCreateSecret(dataDir)
	if err != nil {
		return Config{}, err
	}

	cfg := Config{
		Addr:            env("ADDR", ":8080"),
		DataDir:         dataDir,
		Dev:             dev,
		LogLevel:        strings.ToLower(env("LOG_LEVEL", "info")),
		TrustProxy:      envBool("TRUST_PROXY", false),
		TrustedProxies:  envList("TRUSTED_PROXIES"),
		TrustCloudflare: envBool("TRUST_CLOUDFLARE", false),
		AllowedOrigins:  envList("ALLOWED_ORIGINS"),
		PluginDir:       env("PLUGIN_DIR", ""),
		SecretKey:       secret,

		generatedSecret: generated,

		Database: Database{
			Driver:       driver,
			DSN:          dsn,
			MaxOpenConns: envInt("DB_MAX_CONNS", maxConns),
			// As many idle as open. database/sql closes a released connection
			// whenever the idle set is full, so an idle cap below the open cap
			// means every burst above it pays for a new connection — a TCP
			// handshake, authentication and a fresh backend on Postgres, the
			// schema and pragmas again on SQLite — and throws away that
			// connection's prepared statements. ConnMaxIdle below is what lets
			// a quiet instance give them back.
			MaxIdleConns: envInt("DB_MAX_IDLE_CONNS", maxConns),
			ConnMaxIdle:  envDuration("DB_CONN_MAX_IDLE", 5*time.Minute),
		},
		Session: Session{
			TTL:           envDuration("SESSION_TTL", 30*24*time.Hour),
			CookieName:    env("SESSION_COOKIE", "obsidian_session"),
			SecureCookie:  envBool("COOKIE_SECURE", !dev),
			TouchInterval: envDuration("SESSION_TOUCH_INTERVAL", time.Hour),
		},
		Mail: Mail{
			Host:     env("SMTP_HOST", ""),
			Port:     envInt("SMTP_PORT", 587),
			Username: env("SMTP_USERNAME", ""),
			Password: env("SMTP_PASSWORD", ""),
			From:     env("SMTP_FROM", ""),
			// 465 is implicit TLS everywhere it is offered, so defaulting from
			// the port saves the one setting operators most often miss.
			ImplicitTLS: envBool("SMTP_TLS", envInt("SMTP_PORT", 587) == 465),
			PublicURL:   env("PUBLIC_URL", ""),
		},
		Password: Password{
			Memory:      uint32(envInt("ARGON_MEMORY_KIB", 19456)),
			Iterations:  uint32(envInt("ARGON_ITERATIONS", 2)),
			Parallelism: uint8(envInt("ARGON_PARALLELISM", 1)),
			SaltLength:  16,
			KeyLength:   32,
			MaxParallel: envInt("ARGON_MAX_PARALLEL", min(4, runtime.NumCPU())),
		},
		Upstream: Upstream{
			DialTimeout:           envDuration("UPSTREAM_DIAL_TIMEOUT", 10*time.Second),
			ResponseHeaderTimeout: envDuration("UPSTREAM_HEADER_TIMEOUT", 90*time.Second),
			RequestTimeout:        envDuration("UPSTREAM_REQUEST_TIMEOUT", 0),
			MaxIdleConns:          envInt("UPSTREAM_MAX_IDLE_CONNS", 32),
			IdleConnTimeout:       envDuration("UPSTREAM_IDLE_TIMEOUT", 90*time.Second),
		},
		Bootstrap: Bootstrap{
			Username: env("ADMIN_USER", ""),
			Password: env("ADMIN_PASSWORD", ""),
			Email:    env("ADMIN_EMAIL", ""),
		},
		Console: Console{
			SSHAddr:        env("SSH_ADDR", ""),
			SSHHostKey:     env("SSH_HOST_KEY", filepath.Join(dataDir, SSHHostKeyFile)),
			SSHIdle:        envDuration("SSH_IDLE", 30*time.Minute),
			SSHMaxSessions: envInt("SSH_MAX_SESSIONS", 16),
		},
	}

	if cfg.Password.MaxParallel < 1 {
		cfg.Password.MaxParallel = 1
	}
	if cfg.Database.MaxIdleConns > cfg.Database.MaxOpenConns {
		cfg.Database.MaxIdleConns = cfg.Database.MaxOpenConns
	}
	return cfg, nil
}

// GeneratedSecret reports whether the key was created by this process rather
// than supplied. main warns once when it was: a generated key lives in the
// data directory, which is fine for one host and wrong for two.
func (c Config) GeneratedSecret() bool { return c.generatedSecret }

// Returns the key, and whether it came from the data directory rather than
// the environment.
//
// A key file that exists is used or refused, never replaced. Replacing it
// re-keys the instance without anyone choosing to: everything sealed under the
// old key stops opening, and the symptoms show up later and far from the cause.
func loadOrCreateSecret(dataDir string) ([]byte, bool, error) {
	if raw := env("SECRET_KEY", ""); raw != "" {
		if len(raw) < minSecretLen {
			return nil, false, fmt.Errorf("%sSECRET_KEY must be at least %d characters", envPrefix, minSecretLen)
		}
		warnIfWeakSecret(envPrefix+"SECRET_KEY", raw)
		return []byte(raw), false, nil
	}

	path := filepath.Join(dataDir, SecretKeyFile)
	existing, err := os.ReadFile(path)
	if err == nil {
		trimmed := strings.TrimSpace(string(existing))
		if len(trimmed) < minSecretLen {
			return nil, false, unusableSecretFile(path)
		}
		warnIfWeakSecret(path, trimmed)
		return []byte(trimmed), true, nil
	}
	if !os.IsNotExist(err) {
		return nil, false, fmt.Errorf("read %s: %w", path, err)
	}
	return createSecretFile(path)
}

// createSecretFile persists a new random key at path, which must not exist.
//
// The key is staged in a temporary file beside path, synced, and then linked
// into place. The link is exclusive as the O_EXCL create it replaces was: two
// processes starting on one empty data directory cannot both win, and the loser
// is refused instead of overwriting the key the winner wrote. Unlike that
// create, the name at path never exists before the key it names is complete, so
// a crash during first start cannot leave an empty file for the next start to
// refuse.
func createSecretFile(path string) ([]byte, bool, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return nil, false, fmt.Errorf("generate secret key: %w", err)
	}
	encoded := hex.EncodeToString(buf)

	if err := publishSecretFile(path, encoded+"\n"); err != nil {
		return nil, false, err
	}
	return []byte(encoded), true, nil
}

// publishSecretFile makes path name a file that holds content, and only ever a
// complete one. Where the filesystem cannot make hard links, the file is created
// in place instead, and the window a crash could hit is what it was before.
func publishSecretFile(path, content string) error {
	dir := filepath.Dir(path)
	staged, err := os.CreateTemp(dir, SecretKeyFile+".tmp-*")
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	stagedName := staged.Name()
	// Removed on every path. Once linked, path is a second name for the same
	// file, so removing this one leaves the key where it belongs.
	defer func() { _ = os.Remove(stagedName) }()

	_, err = staged.WriteString(content)
	if err == nil {
		// The key must be on disk before anything is sealed with it. Otherwise a
		// crash soon after first start can keep the database rows and lose the
		// key that opens them.
		err = staged.Sync()
	}
	if closeErr := staged.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	err = linkSecretFile(stagedName, path)
	if os.IsExist(err) {
		return createdByAnotherStart(path)
	}
	if err != nil {
		// FAT and exFAT, and some network and FUSE mounts, cannot make hard links.
		// A first start there worked before publication by link and must still
		// work, so it creates the file in place rather than failing.
		return createInPlace(path, content)
	}

	// The name is a directory entry, and the key is used once this returns, so
	// the entry must be on disk first. A failure here fails the start but keeps
	// the file: another start may already be reading the same key from it.
	return syncDirectory(dir)
}

// createInPlace creates path with O_EXCL and writes content into it. This is the
// create the key file used before publication by link. It is kept for
// filesystems that cannot link, where the name exists before its contents do.
func createInPlace(path, content string) error {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if os.IsExist(err) {
		return createdByAnotherStart(path)
	}
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}

	_, err = file.WriteString(content)
	if err == nil {
		err = file.Sync()
	}
	if closeErr := file.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		// Nothing was sealed with a key this process never returned, so the
		// half-written file is ours to remove. Leaving it would make the next
		// start refuse, when a clean start could simply generate one.
		_ = os.Remove(path)
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// createdByAnotherStart refuses a start that lost the race to create the key
// file. It is told to start again rather than to read the file, because where
// the winner created the name before writing it, a read here could find the
// file still empty.
func createdByAnotherStart(path string) error {
	return fmt.Errorf("%s was created by another process while this one was starting; start again to use the key it holds", path)
}

// syncDirectory makes the directory entry durable. Windows cannot open a
// directory to sync it, so the call is skipped there.
func syncDirectory(dir string) error {
	if runtime.GOOS == "windows" {
		return nil
	}
	handle, err := os.Open(dir)
	if err != nil {
		return fmt.Errorf("sync %s: %w", dir, err)
	}
	err = handle.Sync()
	if closeErr := handle.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return fmt.Errorf("sync %s: %w", dir, err)
	}
	return nil
}

// unusableSecretFile refuses a key file that exists without a usable key. It
// names the file and says what to do, because the obvious fixes point in
// opposite directions: restoring the original key keeps sealed values readable,
// and deleting the file only starts over.
func unusableSecretFile(path string) error {
	return fmt.Errorf("%s %w (it needs at least %d characters), and it is not replaced: "+
		"a new key cannot open what was sealed under the original. "+
		"Restore this file from a backup, or set %sSECRET_KEY to the original key. "+
		"Delete the file only if nothing was ever sealed with it",
		path, errUnusableSecretFile, minSecretLen, envPrefix)
}

// errUnusableSecretFile is the refusal unusableSecretFile wraps. A test asks for
// it with errors.Is, so the wording can change without the test following.
var errUnusableSecretFile = errors.New("does not hold a usable secret key")

// linkSecretFile publishes a new key file under its final name. A variable so a
// test can watch the moment the name appears.
var linkSecretFile = os.Link

// minSecretLen is the floor for a key from the environment or from the file,
// the same for both. A shorter key is refused, never used.
const minSecretLen = 16

// minStrongSecretLen is what the warning asks for. The hard floor stays at 16
// so a deployment that already runs on a shorter key keeps starting; the key
// seals provider credentials and two-step secrets, so refusing to boot over it
// would take the whole instance down for a weakness that is the operator's to
// fix on their own schedule.
const minStrongSecretLen = 32

// weakSecretReason says why a key that is long enough to accept is still a
// poor one, or "" when nothing about it stands out. It looks for the things
// that make a key guessable by hand — short, one kind of character, a few
// characters repeated — not for entropy it cannot measure.
func weakSecretReason(key string) string {
	if len(key) < minStrongSecretLen {
		return fmt.Sprintf("it is only %d characters long", len(key))
	}
	var lower, upper, digit, other bool
	distinct := map[rune]struct{}{}
	for _, r := range key {
		distinct[r] = struct{}{}
		switch {
		case r >= 'a' && r <= 'z':
			lower = true
		case r >= 'A' && r <= 'Z':
			upper = true
		case r >= '0' && r <= '9':
			digit = true
		default:
			other = true
		}
	}
	classes := 0
	for _, used := range []bool{lower, upper, digit, other} {
		if used {
			classes++
		}
	}
	switch {
	case classes < 2:
		return "it uses only one kind of character"
	case len(distinct) < 10:
		return fmt.Sprintf("it repeats only %d distinct characters", len(distinct))
	}
	return ""
}

// warnIfWeakSecret logs once at startup. A warning and not an error, for the
// reason minStrongSecretLen gives.
func warnIfWeakSecret(source, key string) {
	reason := weakSecretReason(key)
	if reason == "" {
		return
	}
	slog.Warn("the instance secret key is weak: "+reason+
		"; use at least 32 random characters (for example `openssl rand -hex 32`). "+
		"It seals stored provider keys and two-step secrets, so changing it later "+
		"makes everything sealed with the old one unreadable — choose it before storing credentials",
		"source", source)
}

func env(key, fallback string) string {
	if value, ok := os.LookupEnv(envPrefix + key); ok && value != "" {
		return value
	}
	return fallback
}

func envList(key string) []string {
	raw := env(key, "")
	if raw == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		if trimmed := strings.TrimSpace(part); trimmed != "" {
			out = append(out, trimmed)
		}
	}
	return out
}

func envInt(key string, fallback int) int {
	raw := env(key, "")
	if raw == "" {
		return fallback
	}
	value, err := strconv.Atoi(raw)
	if err != nil {
		return fallback
	}
	return value
}

func envBool(key string, fallback bool) bool {
	raw := env(key, "")
	if raw == "" {
		return fallback
	}
	value, err := strconv.ParseBool(raw)
	if err != nil {
		return fallback
	}
	return value
}

func envDuration(key string, fallback time.Duration) time.Duration {
	raw := env(key, "")
	if raw == "" {
		return fallback
	}
	value, err := time.ParseDuration(raw)
	if err != nil {
		return fallback
	}
	return value
}
