// Package config turns the process environment into the single Config value
// every other module reads. Nothing else in the server calls os.Getenv, so
// "what can be configured" is answerable by reading this one file.
//
// Every setting has a default that makes `./obsidian-arc` a working server:
// SQLite in ./data, a secret key generated and persisted on first run, an
// address on :8080. Deployment is then a matter of overriding the few things
// a real host cares about, not of filling in a required form.
package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
)

const envPrefix = "OBSIDIAN_"

// SecretKeyFile is where a generated key is persisted, relative to DataDir,
// when OBSIDIAN_SECRET_KEY is not set.
const SecretKeyFile = "secret.key"

type Config struct {
	Addr     string
	DataDir  string
	Dev      bool
	LogLevel string
	// Whose forwarded headers are believed. Every rate limit is keyed on
	// the address this produces, so a caller able to choose it has no
	// limits at all.
	TrustProxy bool
	// Exact peers, when the proxy's address is known. Empty with
	// TrustProxy set falls back to the private ranges.
	TrustedProxies []string
	// Extra origins accepted on state-changing requests, beyond the request's
	// own Host. Only needed when the SPA is served from somewhere else.
	AllowedOrigins []string

	Database  Database
	Session   Session
	Password  Password
	Upstream  Upstream
	Bootstrap Bootstrap
	Mail      Mail

	// Encrypts provider API keys at rest. Never logged, never served.
	SecretKey []byte

	// True when SecretKey was generated by this process instead of supplied.
	generatedSecret bool
}

// Mail is optional. Without a host the server simply cannot offer the
// features that need it, which is a state the admin screen reports rather
// than a misconfiguration. Credentials come from the environment and not
// from the settings table, because that table is served to a browser.
type Mail struct {
	Host     string
	Port     int
	Username string
	Password string
	From     string
	// Implicit TLS from the first byte, as on 465. Otherwise the session
	// starts plain and is upgraded with STARTTLS, which is what 587 wants.
	ImplicitTLS bool
	// What a link in an outgoing message points at. The server cannot
	// infer this: the Host header of whichever request happened to
	// trigger the mail is not a base URL worth trusting.
	PublicURL string
}

type Database struct {
	Driver string // "sqlite" | "postgres"
	DSN    string
	// Ceiling on pooled connections. SQLite in WAL mode tolerates a handful
	// of concurrent readers; Postgres wants a small pool per instance.
	MaxOpenConns int
	MaxIdleConns int
	ConnMaxIdle  time.Duration
}

type Session struct {
	TTL          time.Duration
	CookieName   string
	SecureCookie bool
	// How stale sessions.last_seen_at may get before a request refreshes it.
	// Writing on every request would turn every read into a write.
	TouchInterval time.Duration
}

// Password holds the Argon2id parameters. The defaults are OWASP's second
// recommended profile (19 MiB, t=2, p=1); MaxParallel bounds how many hashes
// may run at once, so a burst of logins cannot multiply that memory cost
// across the whole process.
type Password struct {
	Memory      uint32
	Iterations  uint32
	Parallelism uint8
	SaltLength  uint32
	KeyLength   uint32
	MaxParallel int
}

type Upstream struct {
	DialTimeout           time.Duration
	ResponseHeaderTimeout time.Duration
	// Overall ceiling on one upstream call. Zero means no ceiling beyond the
	// request context, which is what a long generation needs.
	RequestTimeout  time.Duration
	MaxIdleConns    int
	IdleConnTimeout time.Duration
}

// Bootstrap is the first administrator, created only when the users table is
// empty. Leaving it unset on an empty database is not an error: the first
// account registered through the UI is promoted instead.
type Bootstrap struct {
	Username string
	Password string
	Email    string
}

func Load() (Config, error) {
	dataDir := env("DATA_DIR", "./data")
	abs, err := filepath.Abs(dataDir)
	if err != nil {
		return Config{}, fmt.Errorf("resolve data dir %q: %w", dataDir, err)
	}
	dataDir = abs
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		return Config{}, fmt.Errorf("create data dir %q: %w", dataDir, err)
	}

	dev := envBool("DEV", false)

	driver := strings.ToLower(env("DB_DRIVER", "sqlite"))
	switch driver {
	case "sqlite", "sqlite3":
		driver = "sqlite"
	case "postgres", "postgresql", "pgx":
		driver = "postgres"
	default:
		return Config{}, fmt.Errorf("unknown %sDB_DRIVER %q (want sqlite or postgres)", envPrefix, driver)
	}

	dsn := env("DB_DSN", "")
	if dsn == "" {
		if driver != "sqlite" {
			return Config{}, fmt.Errorf("%sDB_DSN is required when %sDB_DRIVER is %s", envPrefix, envPrefix, driver)
		}
		dsn = filepath.Join(dataDir, "obsidian.db")
	}

	// SQLite serialises writers no matter how many handles are open, so a
	// large pool buys nothing and costs file descriptors.
	maxConns := 4
	if driver == "postgres" {
		maxConns = 10
	}

	secret, generated, err := loadOrCreateSecret(dataDir)
	if err != nil {
		return Config{}, err
	}

	cfg := Config{
		Addr:           env("ADDR", ":8080"),
		DataDir:        dataDir,
		Dev:            dev,
		LogLevel:       strings.ToLower(env("LOG_LEVEL", "info")),
		TrustProxy:     envBool("TRUST_PROXY", false),
		TrustedProxies: envList("TRUSTED_PROXIES"),
		AllowedOrigins: envList("ALLOWED_ORIGINS"),
		SecretKey:      secret,

		generatedSecret: generated,

		Database: Database{
			Driver:       driver,
			DSN:          dsn,
			MaxOpenConns: envInt("DB_MAX_CONNS", maxConns),
			MaxIdleConns: envInt("DB_MAX_IDLE_CONNS", 2),
			ConnMaxIdle:  envDuration("DB_CONN_MAX_IDLE", 5*time.Minute),
		},
		Session: Session{
			TTL:           envDuration("SESSION_TTL", 30*24*time.Hour),
			CookieName:    env("SESSION_COOKIE", "obsidian_session"),
			SecureCookie:  envBool("COOKIE_SECURE", !dev),
			TouchInterval: envDuration("SESSION_TOUCH_INTERVAL", time.Hour),
		},
		Mail: Mail{
			Host:     env("SMTP_HOST", ""),
			Port:     envInt("SMTP_PORT", 587),
			Username: env("SMTP_USERNAME", ""),
			Password: env("SMTP_PASSWORD", ""),
			From:     env("SMTP_FROM", ""),
			// 465 is implicit TLS everywhere it is offered, so defaulting from
			// the port saves the one setting operators most often miss.
			ImplicitTLS: envBool("SMTP_TLS", envInt("SMTP_PORT", 587) == 465),
			PublicURL:   env("PUBLIC_URL", ""),
		},
		Password: Password{
			Memory:      uint32(envInt("ARGON_MEMORY_KIB", 19456)),
			Iterations:  uint32(envInt("ARGON_ITERATIONS", 2)),
			Parallelism: uint8(envInt("ARGON_PARALLELISM", 1)),
			SaltLength:  16,
			KeyLength:   32,
			MaxParallel: envInt("ARGON_MAX_PARALLEL", min(4, runtime.NumCPU())),
		},
		Upstream: Upstream{
			DialTimeout:           envDuration("UPSTREAM_DIAL_TIMEOUT", 10*time.Second),
			ResponseHeaderTimeout: envDuration("UPSTREAM_HEADER_TIMEOUT", 90*time.Second),
			RequestTimeout:        envDuration("UPSTREAM_REQUEST_TIMEOUT", 0),
			MaxIdleConns:          envInt("UPSTREAM_MAX_IDLE_CONNS", 32),
			IdleConnTimeout:       envDuration("UPSTREAM_IDLE_TIMEOUT", 90*time.Second),
		},
		Bootstrap: Bootstrap{
			Username: env("ADMIN_USER", ""),
			Password: env("ADMIN_PASSWORD", ""),
			Email:    env("ADMIN_EMAIL", ""),
		},
	}

	if cfg.Password.MaxParallel < 1 {
		cfg.Password.MaxParallel = 1
	}
	if cfg.Database.MaxIdleConns > cfg.Database.MaxOpenConns {
		cfg.Database.MaxIdleConns = cfg.Database.MaxOpenConns
	}
	return cfg, nil
}

// GeneratedSecret reports whether the key was created by this process rather
// than supplied. main warns once when it was: a generated key lives in the
// data directory, which is fine for one host and wrong for two.
func (c Config) GeneratedSecret() bool { return c.generatedSecret }

// Returns the key, and whether it came from the data directory rather than
// the environment.
func loadOrCreateSecret(dataDir string) ([]byte, bool, error) {
	if raw := env("SECRET_KEY", ""); raw != "" {
		if len(raw) < 16 {
			return nil, false, fmt.Errorf("%sSECRET_KEY must be at least 16 characters", envPrefix)
		}
		return []byte(raw), false, nil
	}

	path := filepath.Join(dataDir, SecretKeyFile)
	if existing, err := os.ReadFile(path); err == nil {
		trimmed := strings.TrimSpace(string(existing))
		if len(trimmed) >= 16 {
			return []byte(trimmed), true, nil
		}
	} else if !os.IsNotExist(err) {
		return nil, false, fmt.Errorf("read %s: %w", path, err)
	}

	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return nil, false, fmt.Errorf("generate secret key: %w", err)
	}
	encoded := hex.EncodeToString(buf)
	if err := os.WriteFile(path, []byte(encoded+"\n"), 0o600); err != nil {
		return nil, false, fmt.Errorf("write %s: %w", path, err)
	}
	return []byte(encoded), true, nil
}

func env(key, fallback string) string {
	if value, ok := os.LookupEnv(envPrefix + key); ok && value != "" {
		return value
	}
	return fallback
}

func envList(key string) []string {
	raw := env(key, "")
	if raw == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		if trimmed := strings.TrimSpace(part); trimmed != "" {
			out = append(out, trimmed)
		}
	}
	return out
}

func envInt(key string, fallback int) int {
	raw := env(key, "")
	if raw == "" {
		return fallback
	}
	value, err := strconv.Atoi(raw)
	if err != nil {
		return fallback
	}
	return value
}

func envBool(key string, fallback bool) bool {
	raw := env(key, "")
	if raw == "" {
		return fallback
	}
	value, err := strconv.ParseBool(raw)
	if err != nil {
		return fallback
	}
	return value
}

func envDuration(key string, fallback time.Duration) time.Duration {
	raw := env(key, "")
	if raw == "" {
		return fallback
	}
	value, err := time.ParseDuration(raw)
	if err != nil {
		return fallback
	}
	return value
}
